version: "3"
services:

  # GijiNikoru server
  api:
    build: api
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - "./api/src/app:/usr/src/app"
      - "./api/test/app:/usr/test/app"
      - "./api_tmp:/tmp/giji_nikoru"
      - api:/tmp
    environment:
      - PYTHONPATH=/usr
    sysctls:
      net.core.somaxconn: 8192

  # Web server
  web:
    build: web
    ports:
      - "80:80"
    volumes:
      - api:/tmp

  # Chrome extension Maker
  front:
    build: front
    volumes:
      - "./front:/usr/src/app"

  # DB server
  db:
    build: db
    volumes:
      - "./db/config:/etc/mysql/conf.d"
      - "./db/init:/docker-entrypoint-initdb.d"
      - "./db/data:/var/lib/mysql"
      - "./db/dump:/tmp/dump"
      - "./db/input:/tmp/input"
    environment:
      - MYSQL_ROOT_PASSWORD=password

volumes:
  api:
