"""first version

Revision ID: 5543e3b3770c
Revises: 
Create Date: 2018-04-12 21:25:20.141556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5543e3b3770c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('posted_by', sa.String(length=100), nullable=True),
    sa.Column('point', sa.String(length=10), nullable=True),
    sa.Column('was_deleted', sa.Boolean(), nullable=True),
    sa.Column('original_nicorare', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'video_id')
    )
    op.create_table('job_log',
    sa.Column('type', sa.Enum('VIDEO', 'COMMENT', name='joblogtype'), nullable=False),
    sa.Column('status', sa.Enum('ABORTED', 'RUNNING', 'DONE', name='joblogstatus'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('nicoru',
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('comment_id', sa.String(length=100), nullable=False),
    sa.Column('nikorare', sa.Integer(), nullable=True),
    sa.Column('commented_at', sa.String(length=20), nullable=True),
    sa.Column('commented_point', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('video_id', 'comment_id')
    )
    op.create_table('video',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('thumbnail', sa.String(length=200), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('length', sa.String(length=10), nullable=True),
    sa.Column('watch_url', sa.String(length=300), nullable=True),
    sa.Column('posted_by', sa.String(length=30), nullable=True),
    sa.Column('posted_by_name', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('nicoru')
    op.drop_table('job_log')
    op.drop_table('comment')
    # ### end Alembic commands ###
